name: pangeo_lidar
channels:
  - conda-forge
dependencies:
  - dask
  - dask-kubernetes
  - distributed
  - gcsfs
  - geopandas
  - graphviz
  - intake::intake-xarray
  - ipywidgets
  - jupyter
  - jupyter_client
  - jupyterlab_launcher
  - jupyterlab=0.35
  - lz4
  - matplotlib
  - nbserverproxy
  - nodejs
  - nomkl
  - numcodecs
  - numpy
  - pandas
  - pdal
  - python-blosc
  - python-pdal
  - python=3.6
  - rasterio
  - rasterstats
  - scikit-image
  - scikit-learn
  - seaborn
  - shapely
  - xarray
  - zarr

  - pip:
    - kubernetes
    - graphviz
    - "git+https://github.com/Ecotrust/pyFIRS.git"
